### ISSUE TITLE
Shrine setup

### ISSUE THREAD

**Issue by loumarven** [catsky/administrate-field-shrine#5]
Hey, thanks for this gem!
I'm trying out your gem so I could use Shrine in place of Active Storage for file uploads in Administrate.
My question is, what is the ideal setup for Shrine for this gem to work?

I get the following error when I try this gem:
`ActionView::Template::Error (undefined method 'cached_photo_data' for #<Item:0x00007fe51a6272b0>):`

I plan to use Shrine for uploading images and other file types and I thought I could get started with this gem to wrap the use of Shrine.
Thank you!

**Comment by catsky** [comment]
please refer to https://github.com/shrinerb/shrine

try to enable the following, so that  for `cached_photo_data` accessible
Shrine.plugin :cached_attachment_data # enables retaining cached file across form redisplays
Shrine.plugin :restore_cached_data    # extracts metadata for assigned cached files

**Comment by loumarven** [comment]
Thanks! I'm trying that out now.
